# name: build push deploy image

# on:
#   push:
#     branches: [ "main" ]
#     paths-ignore:
#       - 'README.md'

# jobs:
#   build_push_deploy:
#     permissions:
#       contents: read
#       packages : write

#     env:
#       IMAGE_NAME: ${{ vars.GCP_REGION}}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID}}/${{ vars.GCP_REPOSITORY}}/${{ vars.PROJECT_NAME }}-function

#     runs-on: ubuntu-latest
#     steps:
#       - name: Google Auth
#         id: auth
#         uses: 'google-github-actions/auth@v1'
#         with:
#           token_format: "access_token"
#           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#       - name: Log in to the Container registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ vars.GCP_REGION}}-docker.pkg.dev
#           username: oauth2accesstoken
#           password: ${{ steps.auth.outputs.access_token }}
      
#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ${{ env.IMAGE_NAME }}:latest

#       - name: Deploy job to Cloud Run
#         id: deploy_job
#         uses: google-github-actions/deploy-cloudrun@v2
#         with:
#           job: ${{ vars.GCP_CR_JOB_NAME }}
#           region: ${{ vars.GCP_REGION}}
#           image: ${{ env.IMAGE_NAME }}:latest

#       # If required, use the Cloud Run url output in later steps
#       - name: Show Output
#         run: echo ${{ steps.deploy.outputs.url }}
